### ISSUE TITLE
convexdecomposition fails to compile with GCC 6.1: return-statement with no value in function with non-void return type

### ISSUE THREAD

**Issue by morxa** [rdiankov/openrave#398]
In [`3rdparty/convexdecomposition/NvHashMap.h` on line 687](https://github.com/rdiankov/openrave/blob/master/3rdparty/convexdecomposition/NvHashMap.h#L687), there is a return-statement with no value, but the function does not return 'void'. This gives the following compiler error:

    3rdparty/convexdecomposition/vHashMap.h:687:5: error: return-statement with no value, in function returning 'const CONVEX_DECOMPOSITION::Array<T, Alloc>&' [-fpermissive]

Built on Fedora 25 with GCC 6.1.1.
See [this build log](https://thofmann.fedorapeople.org/openrave-build.log) for more information.

**Comment by rdiankov** [comment]
thanks!
i think the easiest thing is for you to clone this repo and then send a merge request once you get all of it compiling in gcc 6.1
